"""Initial migration

Revision ID: 910beb2be1cb
Revises: 
Create Date: 2024-11-12 09:49:31.785670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '910beb2be1cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('order', 'customer_id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'customer_id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('order', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
